/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intools;

public class App {
    public static void main(String[] args) {
        Main frame = new Main();
        frame.setTitle("InTools");
        frame.setVisible(true);
        frame.pack();
        frame.setLocationRelativeTo(null);
    }
}
